---
- name: juniper initialization playbook #Playbook Name
  hosts: alljuniper #target hosts
#eneable junos module
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no
#new var "credentionales for Netconf over SSH connection"
  vars_prompt:
    - name: "DEVICE_USERNAME"
      promt: "Device username"
      private: no
    - name: "DEVICE_PASSWORD"
      promt: "Device password"
      private: yes
#declare connection var
  vars:
    provider_info:
      host: "{{ inventory_hostname }}"
      username: "{{ DEVICE_USERNAME }}"
      password: "{{ DEVICE_PASSWORD }}"
      port: "{{ ansible_jun_port }}"
      timeout: "{{ ansible_jun_timeout }}"
#TASKS
  tasks:
#check connection
  - name: junos check connection
    wait_for:
      host: "{{ inventory_hostname }}"
      port: "{{ ansible_jun_port }}"
      timeout: 10
#get configs
  - name: "Get committed configuration"
    juniper_junos_config:
        provider: "{{ provider_info }}"
        retrieve: "committed"
    register: response
  - name: "Print result"
    debug:
     var: response
