---
- name: New Tinc service deploy
  hosts: prod_VPS_pptp
  become: no
  
  
  tasks:    
  
   - block:                 #install stuff
   
     - name: Install packages
       yum: name={{ item }} state=latest
       loop:
       - tinc
         
   - block:                 #copy
   
     - name: copy files   
       copy: 
         src: ./tinc/VPS/{{item}} 
         dest: /etc/tinc/VPS/
       with_items:
         ['tinc-down', 'rsa_key.priv' , 'rsa_key.pub']
              
     - name: copy files   
       copy: 
         src: ./tinc/VPS/main 
         dest: /etc/tinc/VPS/hosts/

   - block:                 #generate and copy   
  
     - name: Generate  tinc.conf
       template: src=./tinc/VPS/tinc.j2 dest=/etc/tinc/VPS/tinc.conf
       
     - name: Generate  tinc-up
       template: src=./tinc/VPS/tinc-up.j2 dest=/etc/tinc/VPS/tinc-up
       
  handlers:                 #restart and enable services  
  
  - name:  Restart network
    service: name=network state=restarted
    
  - name:  Restart tinc
    service: name=tinc state=restarted  enabled=yes