---
- name: New Tinc service deploy
  hosts: new_VPS
  become: no


  tasks:

   - block:                 #install stuff

     - name: Install packages
       yum: name={{ item }} state=latest
       loop:
       - epel-release
       - tinc
       - nginx
       - proftpd
       - mc
       - tcpdump
       - iptables
       - iptables-services
       - tree
       - mlocate
       - nmap

   - block:                 #iptables
     - name: Remove and mask service firewalld
       service:
        name: firewalld
        enabled: no
        state: stopped
        masked: yes

   - block:                 #copy new cfg files
     - name: copy tinc keys
       copy:
         src: ./tinc/{{item}}
         dest: /etc/tinc/
       with_items:
         ['tinc-down', 'rsa_key.priv' , 'rsa_key.pub']

     - name: copy cfg tinc
       copy:
         src: ./tinc/main
         dest: /etc/tinc/hosts/

     - name: copy tinc service cfg
       copy:
         src: ./tinc/tinc.service
         dest: /usr/lib/systemd/system/

     - name: copy ifcfg
       copy:
         src: ./tinc/ifcfg-tap0
         dest: /etc/sysconfig/network-scripts/

     - name: copy iptables
       copy:
         src: ./tinc/iptables
         dest: /etc/sysconfig/iptables

   - block:                 #generate and copy tinc configs
     - name: Generate  tinc.conf
       template: src=./tinc/tinc.j2 dest=/etc/tinc/tinc.conf

     - name: Generate  tinc-up
       template: src=./tinc/tinc-up.j2 dest=/etc/tinc/tinc-up

     - name: Changing perm of "tinc-up", adding "+x"
       file: dest=/etc/tinc/tinc-up mode=a+x

     - name: Changing perm of "tinc-down", adding "+x"
       file: dest=/etc/tinc/tinc-down mode=a+x

   - block:                 #network
     - name: enable  routing
       shell: sysctl net.ipv4.ip_forward=1

     - name: enable  routing
       shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf

   - block:                 #enable stuff
     - name: Enable services
       service: name={{ item }} enabled=yes state=started
       loop:
       - tinc
       - iptables

   - block:                 #restart
     - name: Restart
       reboot:
