---
- name: New VPS deploy
  hosts: new_VPS
  become: no
  
  
  tasks:                    
   - block:                 #install stuff
     - name: Install packages
       yum: name={{ item }} state=latest
       loop:
       - epel-release
       - nginx
       - proftpd
       - mc
       - tcpdump
       - iptables
       - iptables-services
       - tree
       - mlocate
    
   - block:                 #enable stuff
     - name: Enable services
       service: name={{ item }} enabled=yes state=started
       loop:
       - nginx
       - proftpd
     
   - block:                 #iptables
     - name: Remove and mask service firewalld
       service:
        name: firewalld
        enabled: no
        state: stopped      
        masked: yes
        
     - name: copy iptables      
       copy: src=./VPS/iptables dest=/etc/sysconfig/
       
     - name: Enable iptables
       service:
         name: iptables
         enabled: yes
         state: started
         
   - block:                 #network       
     - name: enable  routing
       shell: sysctl net.ipv4.ip_forward=1  
       
     - name: enable  routing      
       shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf 
     
     - name: copy route      
       copy: src=./VPS/route-gre1 dest=/etc/sysconfig/network-scripts/  
       
     - name: Generate  ifcfg-gre1
       template: src=./VPS/ifcfg-gre1.j2 dest=/etc/sysconfig/network-scripts/ifcfg-gre1
       notify: Restart network
       
  handlers:
  - name:  Restart network
    service: name=network state=restarted