---
- name: New VPS deploy
  hosts: new_VPS
  become: no
  
  
  tasks:                    
   - block:                 #install stuff
     - name: Install packages
       yum: name={{ item }} state=latest
       loop:
       - epel-release
       - nginx
       - proftpd
       - mc
       - tcpdump
       - iptables
       - iptables-services
       - tree
       - locate
    
   - block:                 #enable stuff
     - name: Enable services
       service: name={{ item }} enabled=yes state=started
       loop:
       - nginx
       - proftpd
     
   - block:                 #network setup
     - name: Remove and mask service firewalld
       service:
        name: firewalld
        enabled: no
        state: stopped      
        masked: yes
  
     - name: enable  routing
       shell: sysctl net.ipv4.ip_forward=1  
       
     - name: enable  routing      
       shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf 
     
     - name: copy route      
       copy: src=./VPS/{{ item }} dest=/etc/sysconfig/network-scripts/  
       loop:
       - route-gre1
       - ifcfg-gre1
  
     - name: copy iptables      
       copy: src=./VPS/iptables dest=/etc/sysconfig/
       
     - name: Enable iptables
       service:
         name: iptables
         enabled: yes
         state: started
         
           #PR_INNER_IPADDR to ifcfg-gre1  
     - lineinfile:
         path: /etc/sysconfig/network-scripts/ifcfg-gre1
         line: "PEER_INNER_IPADDR={{ PEER_INNER_IPADDR }}"
         
           #MINNER_IPADDR to ifcfg-gre1
     - lineinfile:
         path: /etc/sysconfig/network-scripts/ifcfg-gre1
         line: "MY_INNER_IPADDR={{ MY_INNER_IPADDR }}"
         
     - name: Restart network
       service:
         name: network
         enabled: yes
         state: restarted